version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-pep8:
    working_directory: ~/test
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo pip install flake8
      - run: flake8

workflows:
  main:
    jobs:
      - test-pep8
